version: '3'

services: 
 frontend:
  build: 
   context: . 
   dockerfile: Dockerfile.dev
  ports:
    - "3000:3000"
 
 frontend-test:
  build: 
   context: . 
   dockerfile: Dockerfile.dev
  command: ["npm", "run", "test"] 
